searchTerm can be accessed from noResultsComponent
renrizzolo/react-native-sectioned-multi-select pull request #274
Opened 2022-07-06 13:44 UTC by jorge-cob

noResultsComponent={(searchTerm) => AddItemComponent(searchTerm)}

2022-07-20 00:02 UTC, renrizzolo reviewed
Thanks for the PR.
I think this is fine, although I'm not sure if this prop should be renamed as it goes against the convention of all of the other *Component props.
 
- The propType for `noResultsComponent` now has to be function
- The type def for `noResultsComponent` needs to be updated to reflect the change

2022-07-26 15:42 UTC, jorge-cob commented
Thanks for the feedback. I had some trouble with the naming but I believe I've understood your points. Please let me know if there are further improvements to be made.

2022-08-04 03:06 UTC, renrizzolo requested changes

2022-08-04 03:06 UTC, renrizzolo commented on lib/sectioned-multi-select.js
> +                        callIfFunction(renderNoResults(searchTerm)
`callIfFunction` expects a function. 
I think this can just be `renderNoResults ? renderNoResults(searchTerm) : null`

2023-03-17 09:51 UTC, closed without merging